---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Secure MySQL Installation
  mysql_secure_installation:
    login_password: ''
    root_password: "{{ mysql_root_password }}"
    password_updated: true
    remove_anonymous: yes
    disallow_remote_root: yes
    remove_test_db: yes
    state: present
