---
- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP 8.1 and extensions
  apt:
    name:
      - php8.1
      - php8.1-cli
      - php8.1-fpm
      - php8.1-mysql
      - php8.1-intl
      - php8.1-bcmath
      - php8.1-zip
      - php8.1-mbstring
      - php8.1-curl
      - php8.1-soap
    state: present
